// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "WidgetControllerBase.h"
#include "ShelvesStackingController.generated.h"

enum class EBookCategory : uint8;
class UBookItem;
class AShelfActor;

USTRUCT(BlueprintType)
struct FShelvesStackingSetupPayload
{
	GENERATED_BODY()
	
	FShelvesStackingSetupPayload() = default;
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TObjectPtr<AShelfActor> ShelfActorRef = nullptr;
};

/**
 * 
 */
UCLASS()
class FAYE_API UShelvesStackingController : public UWidgetControllerBase
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintCallable)
	UBookItem* PlaceBookIntoShelf();
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	EBookCategory SelectedCategory;
};
