// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "Engine/DeveloperSettings.h"
#include "InteractionSettings.generated.h"

class UBaseInteractionWidget;

/**
 * 
 */
UCLASS(Config=Game, DefaultConfig, meta=(DisplayName="Interaction System"))
class INTERACTIONSYSTEM_API UInteractionSettings : public UDeveloperSettings
{
	GENERATED_BODY()
	
public:
	
	// Max distance at which interactable will be considered active
	UPROPERTY(Config, EditAnywhere)
	float InteractableMaxDistance = 1000.f;
	
	// Angle from the camera view towards object to consider "in view"
    UPROPERTY(Config, EditAnywhere)
	float InteractableCameraViewAngle = 60.f;
	
	UPROPERTY(Config, EditAnywhere)
	TSubclassOf<UBaseInteractionWidget> DefaultInteractionWidgetClass;
};
