// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "Components/WidgetComponent.h"
#include "InteractionWidgetComponent.generated.h"


UCLASS(ClassGroup=(Custom), meta=(BlueprintSpawnableComponent))
class INTERACTIONSYSTEM_API UInteractionWidgetComponent : public UWidgetComponent
{
	GENERATED_BODY()

public:
	UInteractionWidgetComponent();
	
	UFUNCTION(BlueprintCallable, Category = "Interaction Widget Component")
	void ToggleWidget(bool bActive);
	
	UPROPERTY(EditAnywhere, Category = "Interaction Widget Component")
	FVector2D WidgetOffset;

protected:
	virtual void BeginPlay() override;

};
