// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "Components/BoxComponent.h"
#include "HoverableBoxComponent.generated.h"

DECLARE_DYNAMIC_MULTICAST_DELEGATE(FOnHoveredSignature);
DECLARE_DYNAMIC_MULTICAST_DELEGATE(FOnSelectedSignature);


UCLASS(ClassGroup=(Custom), meta=(BlueprintSpawnableComponent))
class FAYE_API UHoverableBoxComponent : public UBoxComponent
{
	GENERATED_BODY()

public:
	UHoverableBoxComponent();

	
	UPROPERTY(BlueprintAssignable, Category="Collision")
	FOnHoveredSignature OnHovered;
	
	UPROPERTY(BlueprintAssignable, Category="Collision")
	FOnHoveredSignature OnUnhovered;
	
	UPROPERTY(BlueprintAssignable, Category="Collision")
	FOnSelectedSignature OnSelected;
	
	UPROPERTY(BlueprintAssignable, Category="Collision")
	FOnSelectedSignature OnUnselected;
};
