// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "Faye/Interfaces/InventoryInterface.h"
#include "GameFramework/Actor.h"
#include "Phone.generated.h"

UCLASS()
class FAYE_API APhone : public AActor, public IInventoryInterface
{
	GENERATED_BODY()

public:
	APhone();
	virtual void Tick(float DeltaTime) override;
	
	virtual UInventory* GetInventory_Implementation() const override;

protected:
	virtual void BeginPlay() override;
	
	UPROPERTY()
	UInventory* Inventory = nullptr;
};
