// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "Item.h"
#include "Faye/Enums/CoffeeTypes.h"
#include "CoffeeItem.generated.h"

USTRUCT(BlueprintType)
struct FCoffeeItemTranslations
{
	GENERATED_BODY()
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TMap<ECoffeeType, FText> CoffeeTypeTranslations;
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TMap<ECoffeeSize, FText> CoffeeSizeTranslations;
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TMap<ECoffeeAddition, FText> CoffeeAdditionsTranslations;
};

/**
 * 
 */
UCLASS()
class FAYE_API UCoffeeItem : public UItem
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	ECoffeeType CoffeeType = ECoffeeType::None;
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	ECoffeeSize CoffeeSize = ECoffeeSize::Small;
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	bool bIced = false;
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	ECoffeeAddition CoffeeAddition = ECoffeeAddition::None;
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	bool bWhippedCream = false;
	
};
