// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "StructUtils/InstancedStruct.h"
#include "UObject/Object.h"
#include "WidgetControllerBase.generated.h"

/**
 * 
 */
UCLASS(BlueprintType, Blueprintable)
class FAYE_API UWidgetControllerBase : public UObject
{
	GENERATED_BODY()
public:
	
	UPROPERTY(BlueprintReadOnly, EditAnywhere)
	FInstancedStruct Payload;
	
	UFUNCTION(BlueprintNativeEvent)
	void InitializeController();
	virtual void InitializeController_Implementation();
	
	void PassPayload(const FInstancedStruct& DataPayload);
};
