// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "UObject/Object.h"
#include "Faye/Structs/ItemDataStruct.h"

#include "Item.generated.h"

/**
 * 
 */
UCLASS(BlueprintType)
class FAYE_API UItem : public UObject
{
	GENERATED_BODY()
	
public:
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	int32 ItemId = -1;
	
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly)
	FText ItemName = FText();
	
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly)
	FText ItemDescription = FText();
	
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly)
	EItemCategory ItemCategory = EItemCategory::None;
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	int32 Price = 0;
};
