#pragma once

#include "CoreMinimal.h"
#include "Engine/DataTable.h"
#include "ItemDataStruct.generated.h"

UENUM(BlueprintType)
enum class EItemCategory : uint8
{
	None,
	Book,
	MAX		UMETA(Hidden)
};

USTRUCT(BlueprintType)
struct FItemDataStruct : public FTableRowBase
{
	GENERATED_BODY()

public:
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	int32 ItemId = 0;
	
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly)
	FText ItemName = FText();
	
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly)
	FText ItemDescription= FText();
	
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly)
	EItemCategory ItemCategory = EItemCategory::None;
};

