// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "Item.h"
#include "Faye/Structs/BookDataStruct.h"
#include "BookItem.generated.h"

/**
 * 
 */
UCLASS()
class FAYE_API UBookItem : public UItem
{
	GENERATED_BODY()
	
public:
	
	void SetupBook(const FBookDataStructRow& Row, int32 InID);
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	EBookCategory BookCategory = EBookCategory::NonFiction;
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	EBookSubCategory BookSubCategory = EBookSubCategory::Biography;
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	int32 PublicationDate = 0;
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FText Author= FText();
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	int32 PageNumber = 0;
};
