// Fill out your copyright notice in the Description page of Project Settings.


#include "BookOnShelfActor.h"


// Sets default values
ABookOnShelfActor::ABookOnShelfActor()
{
	// Set this actor to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;
}

// Called when the game starts or when spawned
void ABookOnShelfActor::BeginPlay()
{
	Super::BeginPlay();
	
}

// Called every frame
void ABookOnShelfActor::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}

