// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/FloatingPawnMovement.h"
#include "NpcPawnMovement.generated.h"

/**
 * 
 */
UCLASS(ClassGroup=Movement, meta=(BlueprintSpawnableComponent))
class FAYE_API UNpcPawnMovement : public UFloatingPawnMovement
{
	GENERATED_BODY()
public:
	UNpcPawnMovement();
protected:
	virtual void BeginPlay() override;
	virtual void TickComponent(float DeltaTime, enum ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;
	void SnapToGround();
	virtual void RequestDirectMove(const FVector& MoveVelocity, bool bForceMaxSpeed) override;
	virtual bool CanStartPathFollowing() const override;
	virtual bool CanStopPathFollowing() const override;
	virtual void RequestPathMove(const FVector& MoveInput) override;
	
	float GroundTraceDistance = 200000.f;
	
	UPROPERTY()
	UCapsuleComponent* OwnerCapsuleComp = nullptr;
};
