// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "Camera/PlayerCameraManager.h"
#include "FayeCameraManager.generated.h"

class USpringArmComponent;
class UCameraComponent;
/**
 * 
 */
UCLASS()
class FAYE_API AFayeCameraManager : public APlayerCameraManager
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintImplementableEvent)
	void ZoomIn(float Amount);
	
	UFUNCTION(BlueprintCallable)
	void ToggleClassRendering(UClass* Class, bool bActive);
	
protected:
	
	virtual void BeginPlay() override;
	
	UPROPERTY(EditAnywhere, BlueprintReadOnly, meta = (AllowPrivateAccess = true))
	USpringArmComponent* SpringArm;
	
	UPROPERTY(EditAnywhere, BlueprintReadOnly, meta = (AllowPrivateAccess = true))
	UCameraComponent* Camera;
	
	UPROPERTY()
	TArray<AActor*> HiddenActors;
};
