// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "Engine/StaticMeshActor.h"
#include "BookOnShelfActor.generated.h"

UCLASS()
class FAYE_API ABookOnShelfActor : public AStaticMeshActor
{
	GENERATED_BODY()

public:
	// Sets default values for this actor's properties
	ABookOnShelfActor();
	
	UFUNCTION(BlueprintImplementableEvent, BlueprintCallable)
	void Select();
	
	UFUNCTION(BlueprintImplementableEvent, BlueprintCallable)
	void Deselect();

protected:
	// Called when the game starts or when spawned
	virtual void BeginPlay() override;

public:
	// Called every frame
	virtual void Tick(float DeltaTime) override;
};
