// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "ShopListDataAsset.generated.h"

enum class EBookCategory : uint8;

USTRUCT(BlueprintType)
struct FItemSaleDataStruct
{
	GENERATED_BODY()
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FText SaleItemName = FText();
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FText SaleItemDescription = FText();
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	int32 BaseCost = 0;
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TMap<EBookCategory, int32> CategoryDropWeight;
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	int32 DropAmount = 0;
};

/**
 * 
 */
UCLASS()
class FAYE_API UShopListDataAsset : public UDataAsset
{
	GENERATED_BODY()
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<FItemSaleDataStruct> SalesItemsList;
};
